server:
  port: 8080


spring:
  profiles:
    active: dev
    group:
      dev:
        - dev
      prod:
        - prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update

server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: bns-ssl

decorator:
  datasource:
    p6spy:
      enable-logging: false

---

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate.ddl-auto: validate
    properties.hibernate.format_sql: false
  
decorator:
  datasource:
    p6spy:
      enable-logging: false

