server:
  port: 8080
  ssl:
    enabled: true
    key-store: ${KEY}
    key-store-password: ${KEY_PASSWORD}
    key-store-type: ${KEY_TYPE}
    key-alias: ${KEY_ALIAS}


spring:
  profiles:
    active: dev
    group:
      dev:
        - dev
      prod:
        - prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB}?serverTimezone=Asia/Seoul
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

---

spring:
  config:
    activate:
      on-profile: dev

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    generate-ddl: true

    show-sql: true
    properties.hibernate.format_sql: true

    hibernate.ddl-auto: create

---

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate.ddl-auto: none
    properties.hibernate.format_sql: false

